services:
  gw-demo.api:
    image: gw-demo.api
    build:
      context: .
      dockerfile: Gw-Demo.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - backend
    ports:
      - 8080:8080

  krakend:
    image: devopsfaith/krakend:latest
    volumes:
      - "./Gw-Demo.KrakenD:/etc/krakend"
    ports:
      - "8081:8080"
    networks:
      - backend
    command: [ "run", "-dc", "krakend.json" ]

  # PostgreSQL - Kong'un veritabanı için gerekli
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    networks:
      - backend
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  ocelot:
    image: ocelot.api
    build:
      context: .
      dockerfile: Gw-Demo.Ocelot/Gw-Demo.Ocelot.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - "./Gw-Demo.Ocelot/Gw-Demo.Ocelot.Api/ocelot.json:/app/ocelot.json" # Ocelot konfigürasyonu mount edildi
    networks:
      - backend
    ports:
      - "8082:80" # Ocelot için port ayarlandı
    command: [ "dotnet", "Ocelot.Api.dll" ] # Ocelot'u başlat
  traefik:
    image: traefik:v2.5
    command:
      - --api.insecure=true
      - --providers.file.filename=/etc/traefik/traefik.yaml
    ports:
      - "8083:8080"
    volumes:
      - ./Gw-Demo.Traefik:/etc/traefik
  # Kong API Gateway
  kong:
    image: kong/kong-gateway:latest
    restart: always
    depends_on:
      - postgres
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: postgres
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
    ports:
      - "8000:8000" # API Gateway (Public)
      - "8443:8443" # API Gateway HTTPS
      - "8001:8001" # Admin API
      - "8444:8444" # Admin API HTTPS
    networks:
      - backend
networks:
  backend:

volumes:
  postgres_data: