services:
  gw-demo.api:
    image: gw-demo.api
    build:
      context: .
      dockerfile: Gw-Demo.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - backend
    ports:
      - 8080:8080
  krakend:
    image: devopsfaith/krakend:latest
    volumes:
      - "./Gw-Demo.KrakenD:/etc/krakend"
    ports:
      - "8081:8080"
    networks:
      - backend
    command: [ "run", "-dc", "krakend.json" ]
networks:
  backend: